# Generated by Django 4.0.5 on 2022-07-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyimage', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
