# Generated by Django 4.0.6 on 2022-07-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_story_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='imagename',
            field=models.TextField(default=''),
        ),
    ]
