# Generated by Django 4.0.5 on 2022-07-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_story_imagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='storyimage',
            field=models.ImageField(upload_to=''),
        ),
    ]
