# Generated by Django 4.0.5 on 2022-07-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='writer',
            field=models.TextField(default=''),
        ),
    ]
